import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";

import NextjsLoading from "@/components/global/loading/NextjsLoadingTop";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Online Courses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {/* <SessionProvider session={sesssion}> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextjsLoading />
          {children}
          <Toaster />
        </ThemeProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
